source 'https://rubygems.org'

gem "compass"
gem "breakpoint", "=2.0.7"
gem "selenium-webdriver"
gem "rspec", "~> 2.14.1"
gem "rspec-expectations"
gem "rspec_junit_formatter"
gem "ci_reporter"
gem "mongo"
gem "bson_ext"
