source 'http://rubygems.org'

gem 'rake'
gem 'rspec'
gem 'cucumber'
gem 'selenium-webdriver'
gem 'rubocop',    			      '=0.18.1'
gem 'httparty'
gem 'jsonpath'
gem 'parallel',               '=1.1.2'

gem 'fog',                    '=1.21.0'
gem 'macaddr',                '=1.6.7'
gem 'vistarpc4r', '=0.3.0'
