EXTENDED_TIMEOUT = 30
ALLOW_INITIAL_LOAD = 30

# KODAK login details
FACILITY_KODAK = 'KODAK'
ACCESS_CODE_KODAK = 'pu1234'
VERIFY_CODE_KODAK = 'pu1234!!'

# PANORAMA login details
FACILITY_PANORAMA = 'PANORAMA'
ACCESS_CODE_PANORAMA = 'pu1234'
VERIFY_CODE_PANORAMA = 'pu1234!!'
APPLET_LOAD_TIME = 15

# MODAL TITLES
ORDER_MODAL_TITLE = 'Order a Lab Test'

# Patients
TEN_PATIENT = 'Ten,Patient'
EIGHT_PATIENT = 'Eight,Patient'
TWO_PATIENT = 'two,patient'
EMPLOYEE_ONE = 'employee,one'
FOURHUNDREDSEVENTY_PATIENT = 'Fourhundredseventy,Patient'
FOURHUNDREDSEVENTYONE_PATIENT = 'Fourhundredseventyone,Patient'

# T-Shirt Size Timeout
SMALL_TIMEOUT = 10
MEDIUM_TIMEOUT = 20
LARGE_TIMEOUT = 30
XLARGE_TIMEOUT = 60

# MODAL TITLES
# ORDER_MODAL_TITLE = 'Order a Lab Test'
