define([], function() {
	var mappings = {
		clinicalreminders_priority: 'Priority of the clinical reminder',
		clinicalreminders_title: 'Title of the clinical reminder',
		clinicalreminders_type: 'Clinical reminder type',
		clinicalreminders_duedate: 'Clinical reminder due date',
		clinicalreminders_donedate: 'Clinical reminder done date',

		encounters_encounter: 'Encounter',
		encounters_hxoccurance: 'Hx Occurance',
		encounters_last: 'Encounter last event',
		encounters_datetime: 'Encounter date',
		encounters_activity: 'Activity of the encounter',
		encounters_type: 'Type of the encounter',
		encounters_enteredby: 'Encounter entered by',
		encounters_facility: 'Facility of the encounter',

		reports_date: 'Report Date',
		reports_type: 'Type of the report',
		reports_enteredby: 'Report entered by',
		reports_facility: 'Facility of the report',
		reports_description: 'Report description',

		conditions_problem: 'Problem name',
		conditions_acuity: 'Acuity of the problem',
		conditions_last: 'Last event',
		conditions_hxoccurance: 'Hx Occurance',
		conditions_description: 'Problem description',
		conditions_standardizeddescription: 'Standardized description',
		conditions_onsetdate: 'Problem onset date',
		conditions_lastupdated: 'Problem last updated time',
		conditions_provider: 'Provider',
		conditions_facility: 'Facility',
		conditions_onset: 'Problem onset',

		medications_medication: 'Medication',
		medications_refills: 'Medication Refills',
		medications_change: 'Change',
		medications_last: 'Last',
		medications_facility: 'Facility',
		medications_name: 'Name',
		medications_sig: 'Sig',
		medications_next: 'Next',

		vitals_description: 'Description',
		vitals_results: 'Results',
		vitals_result: 'Result',
		vitals_last: 'Last',
		vitals_dateobserved: 'Date Observed',
		vitals_type: 'Type',
		vitals_dateentered: 'Date Entered',
		vitals_qualifiers: 'Qualifiers',
		vitals_facility: 'Facility',

		immunizations_vaccinename: 'Vaccine Name',
		immunizations_reaction: 'Reaction',
		immuninizations_date: 'Date',
		immuninizations_facility: 'Facility',
		immuninizations_standardizedname: 'Standardized Name',
		immuninizations_series: 'Series',
		immuninizations_repeatcontraindicated: 'Repeat Containdicated',

		allergies_allergenName: 'Allergen Name',
		allergies_reaction: 'Reaction',
		allergies_severity: 'Severity',
		allergies_standardizedAllergen: 'Standardized Allergen',
		allergies_drugClass: 'Drug Class',
		allergies_enteredBy: 'Entered By',
		allergies_facility: 'Facility',

		labresults_description: 'Description',
		labresults_results: 'Results',
		labresults_last: 'Last',
		labresults_date: 'Date',
		labresults_labtest: 'Lab Test',
		labresults_flag: 'Flag',
		labresults_result: 'Lab Result Result',
		labresults_unit: 'Unit',
		labresults_refrange: 'Ref Range',
		labrestuls_facility: 'Facility',

		visits_date: 'Date',
		visits_description: 'Description',
		visits_location: 'Location',
		visits_facility: 'Facility',
		visits_type: 'Type',
		visits_provider: 'Provider',
		visits_reason: 'Reason',

		chs_date: 'Date',
		chs_authoringinstitution: 'Authoring Institution',
		chs_description: 'Description',

		orders_orderdate: 'Date',
		orders_status: 'Status',
		orders_order: 'Order',
		orders_facility: 'Facility',
		orders_providername: 'Provider Name',
		orders_startdate: 'Start Date',
		orders_stopdate: 'Stop Date',
		orders_type: 'Type',

		timeline_datetime: 'Date & Time',
		timeline_activity: 'Activity',
		timeline_type: 'Type',
		timeline_enteredby: 'Entered By',
		timeline_facility: 'Facility',

		documents_date: 'Date',
		documents_description: 'Description',
		documents_type: 'Type',
		documents_enteredby: 'Entered By',
		documents_facility: 'Facility',

		postings: 'Postings',
		timeline_dateinterval: 'Date interval',
		timeline_graph: 'Graph',

		toolbar_infobutton: 'Infobutton',
		toolbar_detailview: 'Detail',
		toolbar_deletestackedgraph: 'Delete stacked graph',
		toolbar_tilesortbutton: 'Title sort button',
		toolbar_submenu: 'Submenu',
		toolbar_quicklook: 'Quicklook',

		patientSync_mySite: 'Patient sync my site',
		patientSync_allVA: 'Patient sync all VA',
		patientSync_DoD: 'Patient sync DoD',
		patientSync_community: 'Patient sync community'

	};


	return mappings;
});