source 'http://rubygems.org'

gem 'rake'
gem 'rspec',				  '=2.14.1'
gem 'cucumber'
gem 'selenium-webdriver',     '=2.41.0'
gem 'rubocop',    			  '=0.18.1'
gem 'httparty'
gem 'jsonpath'

gem 'fog',                    '=1.21.0'
gem 'macaddr',                '=1.6.7'
