Ext.define('gov.va.hmp.team.Person', {
    extend:'Ext.data.Model',
    idProperty:'uid',
    fields:[
        {
            name:'uid',
            type:'string'
        },
        {
            name:'displayName',
            type:'string'
        },
        {
            name:'displayTitle',
            type:'string'
        },
        {
            name:'displayService',
            type:'string'
        },
        {
            name:'digitalPager',
            type:'string'
        },
        {
            name:'voicePager',
            type:'string'
        },
        {
            name:'fax',
            type:'string'
        },
        {
            name:'photoHRef',
            type:'string'
        }
    ]
});